#!/usr/bin/env ruby

# This script runs the rspec_n executable.
#
# EXECUTION
#
# rspec_n     # Run the project's RSpec test suite 10 times.
# rspec_n N   # Run the projects's test suite N times.
#
# EXIT STATUS
#
# See below for exit status codes and their meaning.

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "cri"
require "fileutils"
require "rspec_n/version"
require "rspec_n/constants"
require "rspec_n/helpers/arguments_helper"
require "rspec_n/errors/bad_option"

# rubocop:disable Metrics/BlockLength
command = Cri::Command.define do
  usage       'rspec_n [iterations] [options]'
  description "rspec_n is an executable installed by the rspec_n Ruby gem.  It provides a " \
              "way to re-run an RSpec test suite 'N' times, which is useful when determining " \
              "if a test suite is consistent.\n\n" \
              "STATUS CODES\n\n" \
              "0 - rspec_n ran successfully                                            \u00A0\n" \
              "1 - problem with the commandline options                                \u00A0"

  flag :h, :help, 'show help' do |_value, cmd|
    puts cmd.help
    exit 0
  end

  command_description = "By default, rspec_n will guess the best command to run RSpec; " \
                        "override it by setting a custom command; wrap the entire command in single or double quotes; " \
                        "join multiple commands with '&&'"
  option :c, :command, command_description, argument: :required

  flag nil, "no-file", "Do not write iteration output to files"

  flag nil, "timestamp", "Write iteration output to a timestamped directory, which can " \
                         "prevent accidental loss. NOTE: It is up to the user to periodically clean up files."

  command_description = "Write iteration output to files in the provided directory " \
                        "rather than the current working directory. Can be used along with the timestamp flag."
  option :d, :dir, command_description, argument: :required

  flag :s, "stop-fast", "Stop when an iteration reports a failure."

  command_description =
    "The order RSpec uses when running specs. Can be one of three values:                          \u00A0\n" \
    "\u00A0\u00A0defined - Run specs in same order           \u00A0\n" \
    "\u00A0\u00A0project - Let project decide                \u00A0\n" \
    "\u00A0\u00A0rand    - Randomize specs (default)"
  option :o, :order, command_description, argument: :required

  flag :v, :version, 'show the current version' do |_value, _cmd|
    puts RspecN::VERSION
    exit 0
  end

  run do |options, args, _cmd|
    require "rspec_n"
    RspecN::Runner.new(options, args).start
  end
end
# rubocop:enable Metrics/BlockLength

begin
  command.run(ArgumentsHelper.arguments)
  exit 0
rescue RspecN::BadOption => e
  warn e.message.colorize(:red)
  exit 1
end
