#!/usr/bin/env ruby

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "rspec_n"

RspecN::Runner.new(count: 2, command: "rm -rf tmp && bundle exec rspec").start
